name: pull_request_closed
on: 
  pull_request:
    types: [closed]
jobs:
  close-pull-request:
    runs-on: ubuntu-latest
    steps:
       - name: TerraformService_Caller_Destroy
         uses: distributhor/workflow-webhook@v1
         env:
          webhook_url: "http://ac3c8268c0e4.ngrok.io/api/terraform/command"
          webhook_secret: "zzzzzzzzzzzzzzzzzzzsasdasgasdasdasd"
          data: '{ "Argument": "destroy", "ArtifactUrl" : "${{github.repository}}", "PrNumber":${{github.event.number}} }'
