name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: TerraformService_Caller
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: "http://807029cb60f1.ngrok.io/api/terraform/test"
          webhook_secret: "zzzzzzzzzzzzzzzzzzzsasdasgasdasdasd"
          data: '{ "weapon": "hammer", "drink" : "beer" }'
