name: learn-github-actions
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: TerraformService_Caller
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: "http://ac3c8268c0e4.ngrok.io/api/terraform/command"
          webhook_secret: "zzzzzzzzzzzzzzzzzzzsasdasgasdasdasd"
          data: '{ "Argument": "GITHUB_REF", "ArtifactUrl" : "${{GITHUB_REF}}", "PrNumber":"${{github.event.number}}" }'
