name: pull_request_actions
on: 
  pull_request:
    types: [opened]
jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
       - name: TerraformService_Caller_Plan
         uses: distributhor/workflow-webhook@v1
         env:
          webhook_url: "http://ac3c8268c0e4.ngrok.io/api/terraform/command"
          webhook_secret: "zzzzzzzzzzzzzzzzzzzsasdasgasdasdasd"
          data: '{ "Argument": "plan", "ArtifactUrl" : "${{github.repository}}", "PrNumber":${{github.event.number}} }'
